#
#
#
# Makefile for bitmap files for fonts project
#
#
# Leo 02Sep88
# revised 15Jun89
#

clean :

install :

SOURCES = Makefile SourcesList
BITMAP_DIRS = Courier Ohlfs Helvetica Times Lexi Symbol

installsrc : 
	mkdirs $(SRCROOT)/bitmapSources
	cp $(SOURCES) $(SRCROOT)/bitmapSources
	cp -r $(BITMAP_DIRS) $(SRCROOT)/bitmapSources




