ROOT = ..
LIBRARY = language
SRCS = 	array.c binaryobject.c dict.c exec.c math.c name.c numstrm.c \
	pa_relocator.c packedarray.c scanner.c stack.c stodevedit.c \
	stodevsupport.c stream.c string.c type.c 
HDRS = 	array.h classarray.h dict.h exec.h grammar.h langdata.h  \
	languagenames.h name.h opcodes.h packedarray.h scanner.h stack.h \
	streampriv.h

MISC = Makefile 

OTHERSWITCHES= -DDPSONLY=1

include $(ROOT)/makefile.common

default-goal: lib


