ROOT = ..
LIBRARY = stream
SRCS = 	clrerr.c fgetc.c fgets.c fputc.c fputs.c gets.c printf.c puts.c \
	scanf.c sprintf.c streamimpl.c unixfopen.c unixstream.c 
HDRS = 	unixstmpriv.h 
ADOBE_OBJS = doprint.o doscan.o

MISC = Makefile 

include $(ROOT)/makefile.common

default-goal: lib

