ROOT = ..
LIBRARY = pslib
SRCS = 	clockunix.c doublink.c except.c os_calloc.c os_malloc.c pool.c sizes.c
ASRCS = maxminsun.s setjmpmach.s

MISC = Makefile 

include $(ROOT)/makefile.common

default-goal: lib




