
/*
    makeNameTable.c

    This is a one file program that takes as input a list of PostScript
    names, namecodes, and namegroups, and outputs a C file with this
    info in a data structure.  Usage:

	    makeNameTable [<infile>]
    
    The file this expects should entirely consist of lines of the form:

    <name> <namecode> <namecode group>
    
    The resulting file will have one large string of all the names
    end-to-end, with separating NULLs, called "_DPSNameTable".  This
    is assumed to be less than 65536 bytes long.  For each group of names
    there will then be an array of unsigned shorts which are offsets
    into the name table.  A names namecode will be used to index into
    one of these arrays.  Finally, all these arrays will form the rows
    of an outermost array.  Given a name's group number, the appropriate
    vector of shorts will be found by negating the group number and
    using that as an index into the outer array.  The outer array will
    have the name _DPSNameOffsetTable.

    Copyright (c) 1988 NeXT, Inc. as an unpublished work.
    All rights reserved.
*/

#include "dpsclient.h"
#include <stdio.h>	
#include <stdlib.h>	
#include <string.h>	

static void error( const char *s );
static void doIt( FILE *inFile,  FILE *outFile );


main( argc, argv )
int argc;
char *argv[];
{
    FILE *inFile;
    FILE *outFile;

    if( argc == 1 )
	inFile = stdin;
    else if ( argc == 2 ) {
	if(!(inFile = fopen( argv[1], "r" ))) {
	    perror(argv[0]);
	    exit( -1 );
	}
    } else {
	fprintf( stderr, "Usage: %s [<infile>]\n", argv[0] );
	exit( -1 );
    }
    outFile = stdout;
    doIt( inFile, outFile );
}

static void
doIt( FILE *inFile,  FILE *outFile )
{
#define MAX_GROUPS	10
#define MAX_NAMES	1000
    char newName[256];
    int newGroup;
    int newNamecode;
    int totalNameLength = 0;
    int groupSize[MAX_GROUPS];		/* amount of namecode vector used */
    short namecodes[MAX_GROUPS][MAX_NAMES];	/* (ab)use that stack */
    int lastGroup = -1;		/* lowest non-possible group */
    int i, j;

    for( i = 0; i < MAX_GROUPS; groupSize[i++] = 0 )
	;
    fprintf( outFile, "#ifdef SHLIB\n#include \"shlib.h\"\n#endif\n" );
    fprintf( outFile, "\n/* this file generated by makeNameTable */\n" );
    fprintf( outFile, "/* Copyright 1988, NeXT, Inc. */\n\n\n" );
    fprintf( outFile, "static const char _DPSNameTable[] = \"\\\n" );
    while( fscanf(inFile, "%s %d %d", newName, &newNamecode, &newGroup) == 3) {
	fprintf( outFile, "%s\\0\\\n", newName );
	newGroup = -newGroup-1;
	if( newGroup != lastGroup ) {
	    if( newGroup != lastGroup+1 )
		error("groups not in consecutive, descending order" );
	    else
		lastGroup = newGroup;
	}
	namecodes[lastGroup][newNamecode] = totalNameLength;
	if( groupSize[lastGroup] < newNamecode+1 )
	    groupSize[lastGroup] = newNamecode+1;
	totalNameLength += strlen(newName)+1;
	if( totalNameLength > 65536 )
	    error("Too many names for 16 bit indices");
    }
    fprintf( outFile, "\";\n\n" );	/* end of DPSNameTable */

    for( i = 0; i <= lastGroup; i++ ) {
	fprintf( outFile, "static const unsigned short array%d[] = {\n", i );
	for( j = 0; j < groupSize[i]; j++ )
	    fprintf( outFile, "%hd,", namecodes[i][j] );
	fprintf( outFile, "\n};\n\n" );
    }
    
    fprintf( outFile,
		"static const unsigned short * const _DPSNameOffsetTable[] = {\n" );
    fprintf( outFile, "\t0,\n" );
    for( i = 0; i <= lastGroup; i++ ) {
	fprintf( outFile, "\tarray%d,\n", i );
    }
    fprintf( outFile, "\n};\n" );
}

static void
error( const char *s )
{
    fprintf( stderr, "ERROR: %s\n", s );
    exit(-1);
}


