ROOT = ..
LIBRARY = vm
SRCS = 	abmimpl.c arguments.c gcimpl.c gcmisc.c gcsharedimpl.c makevm.c \
	recycler.c rgstcmds.c saverestore.c staticdata.c vm.c vm_alloc.c \
	vm_garbage.c vm_memory.c vm_relocate.c vm_segment.c vm_space.c \
	vm_startfile.c 

HDRS = 	abm.h gcinternal.h saverestore.h vm_memory.h vm_relocate.h \
	vm_reverse.h vm_segment.h vm_space.h vmnames.h 

MISC = Makefile

OTHERSWITCHES =

include $(ROOT)/makefile.common

default-goal: lib

