ROOT = ..
LIBRARY = fp
SRCS = 	isinfieee.c mtxvec.c 
ASRCS=	dpintmach.030.s fixedmach.030.s
HDRS = 	os_math.h DEFSmach.h DEFSsun.h

MISC = Makefile 

include $(ROOT)/makefile.common

default-goal: lib

