
/*
    makeExplicitWraps.c

    A little filter to change wraps in to take an explicit context
    parameter.  Usage:

	    makeExplicitWraps [<infile>]
    
    Copyright (c) 1988 NeXT, Inc. as an unpublished work.
    All rights reserved.
*/

#import <stdio.h>
#import <string.h>
extern exit();

#define SKIP_WS(c)  while (*(c) && (*(c) == ' ' || *(c) == '\t')) (c)++;
#define SKIP_TO_WS(c)  while (*(c) && (*(c) != ' ' && *(c) != '\t')) (c)++;

void
fatal(const char *msg)
{
    fprintf(stderr, "makeExplicitWraps error: %s\n", msg);
    exit(-1);
}

void 
doIt(FILE *inFile, FILE *outFile)
{
#define BUF_SIZE 2048
    char         buffer[BUF_SIZE];
    int		 len;
    char	*lParen, *restOfDecl;
    char	*start;

    fprintf(outFile, "/* File generated by makeExplicitWraps */\n");
    while (fgets(buffer, BUF_SIZE, inFile)) {
	if (buffer[strlen(buffer)-1] != '\n')
	    fatal("line too long");
	if (!strncmp(buffer, "defineps ", strlen("defineps "))) {
	    start = buffer;
	    start = strchr(buffer, 'P');
	    if (!start)
		fatal("malformed declaration");
	    fwrite(buffer, 1, start-buffer, outFile);
	    fprintf(outFile, "D");

	    lParen = strchr(start, '(');
	    if (!lParen)
		fatal("malformed declaration");
	    fwrite(start, 1, lParen-start+1, outFile);
	    fprintf(outFile, "DPSContext ctxt");
	    restOfDecl = lParen+1;
	    SKIP_WS(restOfDecl);
	    if (*restOfDecl == ')')
		;
	    else if (*restOfDecl == '|')
		fprintf(outFile, " ");
	    else if (*restOfDecl == '\0')
		fatal("malformed declaration");
	    else
		fprintf(outFile, "; ");
	    fprintf(outFile, "%s", restOfDecl);
	} else
	    fprintf(outFile, "%s", buffer);
    }
}


main(int argc, char *argv[])
{
    FILE        *inFile;
    FILE        *outFile;

    if (argc == 1)
	inFile = stdin;
    else if (argc == 2) {
	if (!(inFile = fopen(argv[1], "r"))) {
	    perror(argv[0]);
	    exit(-1);
	}
    } else {
	fprintf(stderr, "Usage: %s [<infile>]\n", argv[0]);
	exit(-1);
    }
    outFile = stdout;
    doIt(inFile, outFile);
}


