ROOT = ..
LIBRARY = postscript
SRCS = 	contextimpl.c control.c customops.c initmakevm.c package_init.c \
	postscript.c psspace.c 
 
HDRS = postscriptnames.h

MISC = Makefile 

include $(ROOT)/makefile.common

default-goal: lib


