/*
  postscriptnames.h

Copyright (c) 1988 Adobe Systems Incorporated.
All rights reserved.

NOTICE:  All information contained herein is the property of Adobe Systems
Incorporated.  Many of the intellectual and technical concepts contained
herein are proprietary to Adobe, are protected as trade secrets, and are made
available only to Adobe licensees for their internal use.  Any reproduction
or dissemination of this software is strictly forbidden unless prior written
permission is obtained from Adobe.

PostScript is a registered trademark of Adobe Systems Incorporated.
Display PostScript is a trademark of Adobe Systems Incorporated.

Original version: Ed Taft: Thu Jul  7 14:34:27 1988
Edit History:
Ed Taft: Thu Sep 28 16:04:22 1989
Ivor Durham: Wed Aug 24 14:35:25 1988
End Edit History.

Definition of operators and registered names for the postscript package.
This is used both as a C header file and as the input to a shell
script, update_registered_names, that derives a PostScript program
to register the names and one or more C programs to register the
C procedures for the operators.
*/

#ifndef	POSTSCRIPTNAMES_H
#define	POSTSCRIPTNAMES_H

/*
  The following macro defines the package index for this package.
  It must be consistent with the one defined in orphans.h.
 */

#define PACKAGE_INDEX 4  /* = pni_postscript */

/*
  The following macro calls define all standard PostScript operator names
  and their corresponding C procedures. The operators are (or can be)
  divided into multiple operator sets, each corresponding to a distinct
  language extension.

  The first two arguments of the OpSet macro specify a name and a number
  to identify the operator set. The name and number must both be unique
  within the package (the number is regenerated automatically by
  update_registered_names). The third argument identifies the dictionary
  in which the operators are to be registered.
 */

OpSet(ops_postscriptDPS, 1, systemdict)
  Op(condition, PSCondition)
  Op(currentcontext, PSCurrentContext)
  Op(currentshared, PSCurrentShared)
  Op(detach, PSDetach)
  Op(fork, PSFork)
  Op(join, PSJoin)
  Op(lock, PSLock)
  Op(monitor, PSMonitor)
  Op(notify, PSNotify)
  Op(quit, PSQuit)
  Op(realtime, PSRealTime)
  Op(setshared, PSSetShared)
  Op(usertime, PSUserTime)
  Op(wait, PSWait)
  Op(yield, YieldOp)

OpSet(ops_postscriptInternal, 2, internaldict)
  Op(clearinterrupt, PSClrInt)
  Op(disableinterrupt, DisableCC)
  Op(enableinterrupt, EnableCC)

/*
  The following macros define the indices for all registered names
  other than operators. The actual PostScript name is simply
  the macro name with the "nm_" prefix removed.

  The macro definitions are renumbered automatically by the
  update_registered_names script. For ease of maintenance, they
  should be in alphabetical order.
 */

#define nm_handleerror 0
#define nm_interrupt 1
#define nm_timeout 2
#define nm_productdictname 3

/* The following definition is regenerated by update_registered_names */
#define NUM_PACKAGE_NAMES 4

extern PNameObj postscriptNames;

#endif	POSTSCRIPTNAMES_H
