ROOT = ..
LIBRARY = bitmap
SRCS = 	bitmap.c bmlocal.c bmpattern.c \
	bm34.c bm34comp.c bm34conv.c \
	bm38.c bm38comp.c bm38conv.c
#	bm12.c bm12comp.c bm12conv.c bm12moverect.c \
#	bm12funcline.c bm12soverrect.c bm12hlrect.c \
HDRS = 	bitmap.h
MISC = Makefile 

include $(ROOT)/makefile.common

default-goal: lib

