/*
 *     Generated by the NeXT Interface Builder.
 */

#import <stdlib.h>
#import <mach.h>
#import <servers/netname.h>
#import <stdio.h>
#import <strings.h>
#import <defaults.h>
#define c_plusplus 1
#import "/usr/local/include/appkit/pbtypes.h"
#import "/usr/local/include/appkit/pbs.h"
#undef c_plusplus

#define WAIT_TIME	30000

extern int read(), write();

extern const char *NXPostScriptPboardType;
extern const char *NXAsciiPboardType;
extern const char *NXRTFPboardType;
extern const char *NXSelectionPboard;

/* lookup: find a port corresponding to the specified service */
static port_t
lookup_pbs()
{
    port_t              port;
    kern_return_t       ret;	/* note: kern_return_t should be a name
				 * server specific error code */
    char               *host = (char *)NXGetDefaultValue((char *)0, "Host");

    if (!host)
	host = "";
    ret = netname_look_up(name_server_port, host, PBS_NAME, &port);
    if (ret != KERN_SUCCESS)
	return(PORT_NULL);
    return(port);
}

void main(argc, argv)
    int argc;
    char *argv[];
{
    char *ourType;
    const char *PSprefix = "%!PS-Adobe-2.0 EPSF-";
    const char *RTFprefix = "{\\rtf";
    int pbNum;
    port_t pbs_port;
    int waitTime;
    const char *defValue;
    
    if (!(pbs_port = lookup_pbs()))
    {
    	fprintf(stderr,"%s: Cannot lookup pbs server!\n",argv[0]);
	exit(-1);
    }

    defValue = NXGetDefaultValue(NULL, "NXNetTimeout");
    waitTime = defValue ? atoi(defValue) : WAIT_TIME;

    /* If the last letter of argv[0] is y, then do the copy case */
    if ((*(argv[0]+strlen(argv[0])-1)) == 'y')
    {
	char *inputBuffer = NULL;
	int inputSize = 0;
	
	/* Read everything we can from the standard input */
	{
	    int bufferSize = 0,res;
	    
	    while(1) {
		if (inputSize >= bufferSize)
		    if (bufferSize)
			inputBuffer = (char *)realloc(inputBuffer,bufferSize *= 2);
		    else
			inputBuffer = malloc(bufferSize = 8192);
		res = read(0,inputBuffer+inputSize,bufferSize-inputSize);
		if (res == 0) break;
		if (res < 0)
		{
		    fprintf(stderr,"%s: Cannot read stdin",argv[0]);
		    perror("");
		    exit(-1);
		}
		inputSize += res;
	    }
	}
	/* OK, we've got input in inputBuffer and its length in inputSize */
	/* Determine whether or not we've got PostScript here */
	if ((inputSize > strlen(PSprefix)) && 
		    (strncmp(inputBuffer,PSprefix,strlen(PSprefix))==0))
	    ourType = (char *)NXPostScriptPboardType;
	else
	    if ((inputSize > strlen(RTFprefix)) && 
			(strncmp(inputBuffer,RTFprefix,strlen(RTFprefix))==0))
		ourType = (char *)NXRTFPboardType;
	    else
		ourType = (char *)NXAsciiPboardType;
	/* Tell the pbs that we've got one type */
	if (_NXSetTypes(waitTime,pbs_port,(char *)NXSelectionPboard,
		PORT_NULL,0,(data_t)ourType,
		strlen(ourType)+1,1,&pbNum) != PBS_OK)
	{
	    fprintf(stderr,"%s:Cannot set data types!\n",argv[0]);
	    exit(-1);
	}
	/* And write the data for that type */
	if (_NXSetData(waitTime,pbs_port,(char *)NXSelectionPboard,pbNum,
		ourType,inputBuffer,inputSize,&pbNum) != PBS_OK)
	    fprintf(stderr,"%s:Cannot put data type %s!\n",argv[0],ourType);
    } /* end of if in copy state */
    else
    {	/* Implement paste side */
    	char *typeStr,*type,*data;
	unsigned int typeStrLen, length;
	int hasPS=0,hasRTF=0,hasAscii=0;
	int numTypes;
	int preferPS=0,preferRTF=0,preferAscii=0;
	
	/* Find out if we prefer any type */
	if ((argc > 2)&&(strcmp(argv[1],"-Prefer")==0))
	{
	    if (strcmp(argv[2],"ps")==0)
	    	preferPS = 1;
	    if (strcmp(argv[2],"ascii")==0)
	    	preferAscii = 1;
	    if (strcmp(argv[2],"rtf")==0)
	    	preferRTF = 1;
	}
	/* Get the list of types from pbs */
	if (_NXGetTypes(waitTime,pbs_port,(char *)NXSelectionPboard,
			&typeStr,&typeStrLen,&numTypes,&pbNum) != PBS_OK)
	{
	    fprintf(stderr,"%s:Cannot get type list!\n",argv[0]);
	    exit(-1);
	}
	/* Now see which of our three types it has */
	for(type=typeStr;type<(typeStr+typeStrLen);type+=(strlen(type)+1))
	{
	    if (strcmp(type,NXPostScriptPboardType)==0)
	    	hasPS = 1;
	    if (strcmp(type,NXAsciiPboardType)==0)
	    	hasAscii = 1;
	    if (strcmp(type,NXRTFPboardType)==0)
	    	hasRTF = 1;
	}
	type = NULL;
	if (preferPS && hasPS)
	    type = (char *)NXPostScriptPboardType;
	else if (preferRTF && hasRTF)
	    type = (char *)NXRTFPboardType;
	else if (hasAscii)
	    type = (char *)NXAsciiPboardType;
	else if (hasPS)
	    type = (char *)NXPostScriptPboardType;
	else if (hasRTF)
	    type = (char *)NXRTFPboardType;
	else
	    exit(0);
	if (_NXBlockingGetData(waitTime,pbs_port,(char *)NXSelectionPboard,
				type,pbNum,&data,&length,&pbNum) == PBS_OK)
	    write(1,data,length);
	else
	{
	    fprintf(stderr,"%s:Couldn't get data type %s from pbs!\n",
		    argv[0],type);
	    exit(-1);
	}
    } /* of paste state */
} /* main */

void _NXMsgError(kern_return_t errorCode)
{
    fprintf(stderr,"%s:Pasteboard communication error #!\n", errorCode);
    exit(-1);
}
