ROOT = ..
LIBRARY = mousekeyboard
SRCS = common.c kbdroutines.c routines.c
HDRS = vars.h
MISC = Makefile 
OTHERSWITCHES = -DCONTROLLER_TYPE=cont_next1

include $(ROOT)/makefile.common

default-goal: lib

