ROOT = ..
LIBRARY = bintree
SRCS = 	bag.c bitpiece.c bounds.c causeset.c divpiece.c drivers.c extent.c \
	layer.c pattern.c windowlist.c

ASRCS = piece.030.s

HDRS = 	bintreetypes.h

MISC = Makefile 

OTHERSWITCHES= -DCONTROLLER_TYPE=cont_next1

include $(ROOT)/makefile.common


default-goal: lib



